added volume control and device listing options to adb-key; improved help messages in adb-pull and adb-push

diff --git a/ScriptsLinux/adb-key b/ScriptsLinux/adb-key
--- a/ScriptsLinux/adb-key
+++ b/ScriptsLinux/adb-key
@@ -9,6 +9,11 @@ function fn_help () {
     echo "  -i TEXT, --input TEXT     send a text input to a connected device"
     echo "  -K, --keyboard            enter keyboard mode (type keys directly to device)"
     echo "  -ss, --shake              send a shake event to a connected device"
+    echo "  --vol+                    increases the volume on the device"
+    echo "  --vol-                    decreases the volume on the device"
+    echo ""
+    echo "  --devices                 list connected devices"
+    echo ""
     echo "  -s SERIAL                 use device with given serial"
     echo "  -h, --help                show this help"
     echo ""
@@ -21,16 +26,50 @@ function fn_help () {
     echo "  $scriptName -s SERIAL -i \"hello world\""
     echo "  $scriptName -s SERIAL -K"
     echo "  $scriptName -s SERIAL -ss"
+    echo "  $scriptName -s SERIAL --vol+"
+    echo "  $scriptName -s SERIAL --vol-"
+    exit 0
+}
+
+fn_default () {
+    if [ "$1" != "" ]; then echo "$scriptName: invalid option '$2'"; fi
+    echo "Try '$scriptName --help' for more information."
+    exit 1
+}
+
+fn_devices () {
+    adb devices -l
     exit 0
 }
 
 function fn_shake () {
-    if [ $# == 1 ]; then
+    if [[ "$1" != "false" ]]; then
+        adb -s $1 shell input keyevent 82
+        exit 0
+    else
         adb shell input keyevent 82
         exit 0
-    fi 
-    if [ $# == 2 ]; then
-        adb -s $1 shell input keyevent 82
+    fi
+    exit 1
+}
+
+function fn_volumeUp () {
+    if [[ "$1" != "false" ]]; then
+        adb -s $1 shell input keyevent KEYCODE_VOLUME_UP
+        exit 0
+    else
+        adb shell input keyevent KEYCODE_VOLUME_UP
+        exit 0
+    fi
+    exit 1
+}
+
+function fn_volumeDown () {
+    if [[ "$1" != "false" ]]; then
+        adb -s $1 shell input keyevent KEYCODE_VOLUME_DOWN
+        exit 0
+    else
+        adb shell input keyevent KEYCODE_VOLUME_DOWN
         exit 0
     fi
     exit 1
@@ -46,13 +85,12 @@ function fn_keyevent () {
         if [ "$1" == "ESC" ]; then keyCode=ESCAPE; fi
         keyCode=${keyCode^^}
     }
-    if [ $# == 1 ]; then
+    if [[ "$1" != "false" ]]; then
         if [ "$1" == "" ]; then echo "$scriptName: missing KEY operator"; exit 1; fi
         get_key_event $1
         adb shell input keyevent KEYCODE_$keyCode
         exit 0
-    fi 
-    if [ $# == 2 ]; then
+    else
         if [ "$2" == "" ]; then echo "$scriptName: missing KEY operator"; exit 1; fi
         get_key_event $2
         adb -s $1 shell input keyevent KEYCODE_$keyCode
@@ -62,14 +100,13 @@ function fn_keyevent () {
 }
 
 function fn_input () {
-    if [ $# == 1 ]; then
+    if [[ "$1" != "false" ]]; then
         if [ "$1" == "" ]; then echo "$scriptName: missing KEY operator"; exit 1; fi
         text=`echo $2 | sed "s/\s/\%s/g"`
         adb shell input text "$text"
         echo "Written to device > $2" 
         exit 0
-    fi 
-    if [ $# == 2 ]; then
+    else
         if [ "$2" == "" ]; then echo "$scriptName: missing KEY operator"; exit 1; fi
         text=`echo $2 | sed "s/\s/\%s/g"`
         adb -s $1 shell input text "$text"
@@ -130,37 +167,36 @@ function fn_keyboard() {
 }
 
 function main () {
-    if [[ "$*" == *"--help"* ]] || [[ "$*" == *"-h"* ]]; then
-        fn_help
+    if [[ $# == 0 ]]; then
+        echo "$scriptName: requires an argument"
+        exit 1
     fi
 
-    # Args handle
-    if [[ "$1" == "-ss" ]] || [[ "$1" == "--shake" ]] || [[ "$3" == "-ss" ]] || [[ "$3" == "--shake" ]]; then
-        if [ "$#" != 2 ]; then echo "$scriptName: invalid option '$1'"; fi
-        if [ "$#" != 4 ]; then echo "$scriptName: invalid option '$3'"; fi
-        if [ "$#" == 1 ]; then fn_shake; fi
-        if [ "$#" == 3 ]; then fn_shake $2; fi
-    fi
+    if [[ "$*" == *"-h"* ]] || [[ "$*" == *"--help"* ]]; then fn_help; fi
 
-    if [ "$1" == "-k" ] || [ "$1" == "--key" ] || [ "$3" == "-k" ] || [ "$3" == "--key" ]; then
-        if [ "$#" == 2 ]; then fn_keyevent $2; fi
-        if [ "$#" == 4 ]; then fn_keyevent $2 $4; fi
-    fi
-    if [ "$1" == "-i" ] || [ "$1" == "--input" ] || [ "$3" == "-i" ] || [ "$3" == "--input" ]; then
-        if [ "$#" == 2 ]; then fn_input $2; fi
-        if [ "$#" == 4 ]; then fn_input $2 $4; fi
-    fi
-    if [ "$1" == "-K" ] || [ "$1" == "--keyboard" ] || [ "$3" == "-K" ] || [ "$3" == "--keyboard" ]; then
-        if [ "$#" == 1 ]; then fn_keyboard; fi
-        if [ "$#" == 3 ]; then fn_keyboard $2; fi
-    fi
+    device=false
+    [[ "$1" == "-s" ]] && device=$2
+    [[ -z $device ]] && echo "$scriptName: -s requires an argument" && exit 1
 
-    # Nothing done
-    if [ "$1" == "" ]; then echo "$scriptName: missing file operand"; fi
-    if [ "$1" != "" ]; then echo "$scriptName: invalid option '$1'"; fi
-    echo "Try '$scriptName --help' for more information."
-    exit 1
-
+    if [[ "$device" == "false" ]]; then
+        if [[ "$1" == "-ss" ]] || [[ "$1" == "--shake" ]]; then fn_shake $device $2; fi
+        if [[ "$1" == "-k" ]] || [[ "$1" == "--key" ]]; then fn_keyevent $device $2; fi
+        if [[ "$1" == "-i" ]] || [[ "$1" == "--input" ]]; then fn_input $device $2; fi
+        if [[ "$1" == "-K" ]] || [[ "$1" == "--keyboard" ]]; then fn_keyboard $device $2; fi
+        if [[ "$1" == "--vol+" ]]; then fn_volumeUp $device $2; fi
+        if [[ "$1" == "--vol-" ]]; then fn_volumeDown $device $2; fi
+        if [[ "$1" == "--devices" ]]; then fn_devices; fi
+        fn_default $device $1
+    else
+        if [[ "$3" == "-ss" ]] || [[ "$3" == "--shake" ]]; then fn_shake $device $4; fi
+        if [[ "$3" == "-k" ]] || [[ "$3" == "--key" ]]; then fn_keyevent $device $4; fi
+        if [[ "$3" == "-i" ]] || [[ "$3" == "--input" ]]; then fn_input $device $4; fi
+        if [[ "$3" == "--vol+" ]]; then fn_volumeUp $device $4; fi
+        if [[ "$3" == "--vol-" ]]; then fn_volumeDown $device $4; fi
+        if [[ "$3" == "-K" ]] || [[ "$3" == "--keyboard" ]]; then fn_keyboard $device $4; fi
+        if [[ "$3" == "--devices" ]]; then fn_devices; fi
+        fn_default $device $3 
+    fi
 }
 
 main $*
