ln show path

diff --git a/ScriptsLinux/what b/ScriptsLinux/what
--- a/ScriptsLinux/what
+++ b/ScriptsLinux/what
@@ -1,10 +1,15 @@
 #!/bin/bash
+set -e
 
 if [ $# -eq 0 ]; then
-  echo "No arguments provided"
   exit 1
 fi
 
-type $*
-ls -l $(which $*) | awk {'print $9" "$10" "$11'}
-which -a $*
+if ! command -v $1 >/dev/null 2>&1; then
+  echo "what: $1 not found"
+  exit 1
+fi
+
+type $1
+ls -l $(which $1) | awk {'print "main: "$9" "$10" "$11'}
+which -a $1
